FROM almalinux:8
RUN yum install nginx -y
ENV TRAINING="DEVOPS" \
      TRAINER="SIVAKUMAR" \
      DURATION="120 HOURS" 
CMD ["nginx","-g","daemon off;"] # this is executable format. We give every word in seperate quotes.
